name: Scheduled Data Fetch

on:
  # schedule:
  #   - cron: '30 * * * *'
  workflow_dispatch:  # 手動実行のみを許可

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: |
        echo "URL from secrets: $URL"
        bash update.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: noricha-vr/toGithubPagesJson
        publish_branch: gh-pages
        publish_dir: ./docs
